baseURL = "/"
languageCode = "en-us"
title = "Resume | MERT BAKIR"
disableKinds = ["taxonomy", "term", "page", "section", "RSS", "sitemap", "robotsTXT", "404"]
theme = "resume-A4"

[params]
useFontAwesome = true
avatar = "avatar.jpg"

[params.display]
experience = true
education = true
languages = true
awards = true
skills = true
skills_grouped = false
interests = true
contact = false
tagline = true
aboutMe = false
projects = false
papers = false
avatar = true

[params.display.footer]
footer = true
links = true
credits = true

[params.footer]
footnote = "You can print this resume in A4 size or save as pdf. | Last update on 01.09.2020."

[params.footer.links]
[[params.footer.links.link]]
prefix = "Contact me on"
name = "Linkedin"
url = "https://linkedin.com/in/mertbakir/"
icon = "fab fa-linkedin"

[[params.footer.links.link]]
prefix = "Check out my"
name = "Website"
url = "https://mertbakir.gitlab.io/about/"
icon = "fas fa-globe"